### ISSUE TITLE
package body doesn't compile

### ISSUE THREAD

**Issue by pauljdarcy** [ReneNyffenegger/xlsx_writer-Oracle#2]
Hi there,
the package body xlsx_writer.pkb doesn't compile due to the following errors:

PLS-00201: identifier 'ZIPPER.ADDFILE' must be declared
PLS-00201: identifier 'ZIPPER.FINISH' must be declared

Thanks,
Paul

**Comment by ReneNyffenegger** [comment]
Paul, you find the package zipper at https://github.com/ReneNyffenegger/oracle_scriptlets/tree/master/zipper (github repo https://github.com/ReneNyffenegger/oracle_scriptlets - directory zipper).

**Comment by pauljdarcy** [comment]
Thank you very much Rene.  It's compiling perfectly now.  
Apologies for not checking your repository first, I'm very new to github.
All the best,
Paul
